"""增加了slot

Revision ID: 1ac44a7eaa0a
Revises: c88ea9d61322
Create Date: 2024-06-27 21:20:05.012467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac44a7eaa0a'
down_revision = 'c88ea9d61322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slots', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.drop_column('slots')

    # ### end Alembic commands ###
