"""update appointment

Revision ID: c88ea9d61322
Revises: 64bfd029cf82
Create Date: 2024-06-09 16:28:36.892620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88ea9d61322'
down_revision = '64bfd029cf82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('job',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'default_job'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('job',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'default_job'"))

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('doctor_name')
        batch_op.drop_column('patient_name')

    # ### end Alembic commands ###
